{% set name = "sourmash_plugin_directsketch" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sourmash_plugin_directsketch-{{ version }}.tar.gz
  sha256: faedef5c4a0db8b7b6978b684439579ba93a59460eb7a2bec815f636e697e333

build:
  number: 0
  skip: true  # [osx or win or py<310]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - crossenv                            # [build_platform != target_platform]
    - maturin >=1.0,<2.0                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - posix                               # [win]
    - make                                # [unix]
    - cargo-bundle-licenses
    - libclang                            # [unix]
    - clangdev                            # [unix]
    - xz
  host:
    - python
    - maturin >=1.1.0,<2
    - pip
  run:
    - python
    - xz
    - sourmash-minimal >=4.8.3,<5

test:
  imports:
    - sourmash_plugin_directsketch
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sourmash-bio/sourmash_plugin_directsketch
  summary: download and sketch data directly
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ctb
    - bluegenes
